version: '3.8'

services:
  web:
    container_name: qd2_app
    build:
      context: .
      dockerfile: Dockerfile
    image: web-app-qd2:latest
    restart: always
    entrypoint: ["nginx", "-g", "daemon off;"]
    ports:
      - "3017:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
